[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "B", "UP"]

[tool.pytest.ini_options]
addopts = "-q --maxfail=1 --disable-warnings --cov=.: --cov-report=xml --cov-report=term-missing"

[tool.coverage.report]
fail_under = 80
